language: java
install: true

jdk:
  - openjdk11

services:
  - docker

jobs:
  include:
    - stage: Test
      before_script:
        - chmod +x gradlew
      script:
        - ./gradlew clean check
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

    - stage: Build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose up --build -d
        - docker build -t badabin:$TRAVIS_COMMIT .
        - docker images
        - docker tag badabin:$TRAVIS_COMMIT $DOCKER_USERNAME/badabin
        - docker push $DOCKER_USERNAME/badabin
