install: gradle wrapper --gradle-version 5.1.1

language: java
jdk: openjdk11

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean check

after_success:
  - bash <(curl -s https://codecov.io/bash)