language: java
install: true

jdk:
  - openjdk11

services:
  - docker

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean check bootJar
  - echo "Building docker image..."
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t badabin .
  - docker images
  - docker tag badabin $DOCKER_USERNAME/badabin
  - docker push $DOCKER_USERNAME/badabin

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
