version: '3.3'

services:
  badabin:
    build: .
    restart: always
    container_name: badabin-container
    ports:
      - 8080:8080
    working_dir: /
    depends_on:
      - badabin-mongo
      - activemq

  badabin-mongo:
    image: mongo
    container_name: badabin-mongo
    hostname: badabin-mongo
    volumes:
      - $HOME/data/badabin-mongo-data:/data/db
      - $HOME/data/badabin-mongo-bkp:/data/bkp
    restart: always

  activemq:
    image: webcenter/activemq:5.14.3
