version: '3.3'

services:
  badabin:
    build: .
    restart: always
    container_name: badabin
    ports:
      - 8080:8080
    working_dir: /
    depends_on:
      - badabin-db

  badabin-db:
    image: mongo
    container_name: badabin-db
    hostname: badabin-db
    volumes:
      - $HOME/data/badabin-db-data:/data/db
      - $HOME/data/badabin-db-bkp:/data/bkp
    restart: always
